dafny(ASN-0034): TumblerSub translate → verified
verification/dafny/ASN-0034/TumblerSub.dfy(27,14): Warning: unusual indentation in left-hand operand of ==> (which starts at line 26, column 13); do you perhaps need parentheses?
   |
27 |               ==> PositiveTumbler.PositiveTumbler(r)
   |               ^^^

verification/dafny/ASN-0034/TumblerSub.dfy(31,4): Warning: assume statement has no {:axiom} annotation
   |
31 |     assume false;
   |     ^^^^^^

Dafny program verifier finished with 1 verified, 0 errors
Compilation failed because warnings were found and --allow-warnings is false